### ISSUE TITLE
site: membuat database notebook dalam satu file yaml

### ISSUE THREAD

**Issue by taruma** [taruma/hidrokit-nb#49]
Saat ini ada tiga file yml untuk data kategori yaitu `umum.yml`, `hidrokit.yml`, `demo.yml`.
Ketiga file itu bisa digabung menjadi satu file dengan memberi informasi label untuk setiap notebook. Contohnya seperti:
```yaml
- title       : >-
    Prediksi Kualitas Air menggunakan Metode _Artificial Neural Networks_
  notebook    : taruma_demo_ann_ka_2_0_0
  date        : 2019-07-13
  author      : taruma
  version     : 2.0.0
  labels      : umum, hidrokit, demo
```

kemudian nanti di cek apakah `string` kategori ada dalam `labels` atau tidak.
```liquid
{% if item.labels contains "umum" %}
```

untuk generalisasi permasalahan, bisa diubah umum sebagai variabel saat menggunakan `include`.
```liquid
{% if item.labels contains include.categories %}
```

Saya belum sempat coba berhasil tidaknya.

### Referensi
- https://help.shopify.com/en/themes/liquid/basics/operators
